# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1091, 508)
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45); ")
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 271, 321))
        self.groupBox.setStyleSheet("background-color: rgb(45, 45, 45); color: rgb(255, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(20, 30, 231, 31))
        self.comboBox.setStyleSheet("color: rgb(255, 255, 255); background-color: rgb(52, 52, 52);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 70, 231, 31))
        self.comboBox_2.setStyleSheet("color: rgb(255, 255, 255); background-color: rgb(52, 52, 52);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(40, 190, 61, 22))
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255); background-color: rgb(52, 52, 52);")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 160, 55, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(110, 190, 21, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 190, 61, 22))
        self.lineEdit_2.setStyleSheet("color: rgb(255, 255, 255); background-color: rgb(52, 52, 52);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 21, 16))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 240, 61, 16))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(80, 230, 171, 31))
        self.comboBox_3.setStyleSheet("color: rgb(255, 255, 255); background-color: rgb(52, 52, 52);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 280, 141, 16))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 280, 111, 21))
        self.lineEdit_3.setStyleSheet("color: rgb(255, 255, 255); background-color: rgb(52, 52, 52);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setDragEnabled(False)
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(20, 110, 231, 31))
        self.comboBox_4.setStyleSheet(" background-color: rgb(52, 52, 52);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(290, 10, 791, 471))
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"gridline-color: rgb(84, 84, 84);background-color: rgb(52, 52, 52); color: rgb(255, 255, 255)")
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        header = self.tableWidget.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        item = QtWidgets.QTableWidgetItem()
        item.setForeground(QtGui.QColor('black'))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setForeground(QtGui.QColor('black'))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setForeground(QtGui.QColor('black'))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setForeground(QtGui.QColor('black'))
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setForeground(QtGui.QColor('black'))
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(170) #134
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().hide()
        self.tableWidget.setColumnWidth(2, 100)
        self.tableWidget.setColumnWidth(3, 100)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 330, 271, 151))
        self.groupBox_2.setStyleSheet("background-color: rgb(45, 45, 45); color: rgb(255, 255, 255);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 121, 61))
        self.pushButton.setStyleSheet(" color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 20, 121, 61))
        self.pushButton_2.setStyleSheet("background-color: rgb(70, 70, 70); color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber.setGeometry(QtCore.QRect(90, 90, 171, 51))
        self.lcdNumber.setStyleSheet("background-color: rgb(52, 52, 52);")
        self.lcdNumber.setObjectName("lcdNumber")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1091, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Настройки"))
        self.comboBox.setCurrentText(_translate("MainWindow", "Все скины"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Все скины"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Desert Eagle"))
        self.comboBox.setItemText(2, _translate("MainWindow", "AWP"))
        self.comboBox.setItemText(3, _translate("MainWindow", "USP-S"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Все стикеры"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2 одинаковых стикера"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3 одинаковых стикера"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "4 одинаковых стикера"))
        self.label.setText(_translate("MainWindow", "Цена в $"))
        self.label_2.setText(_translate("MainWindow", "до"))
        self.label_3.setText(_translate("MainWindow", "От"))
        self.label_4.setText(_translate("MainWindow", "Запись в:"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "txt"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "excel"))
        self.label_5.setText(_translate("MainWindow", "Количество записей:"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Любое качество"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ссылка"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Скин"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Цена"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Без стикеров"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Качество"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Меню"))
        self.pushButton.setText(_translate("MainWindow", "Пуск"))
        self.pushButton_2.setText(_translate("MainWindow", "Стоп"))
        self.label_6.setText(_translate("MainWindow", "Записано:"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
